AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vanity-name-generator

# Parameters:
#   AppBucketName:
#     Type: String
#     Description: "REQUIRED: Unique S3 bucket name to use for the app."

Resources:
  VanityNumberGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/vanity-number-generator.generateVanityNumbers
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 60
      

  # AppBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Ref AppBucketName
